### PR TITLE
Basic help

### PR DESCRIPTION
**Pull request by troglobit**
This pull request adds basic help text to the tool and updates the README

### CODE REVIEW

**Comment by troglobit** [comment]
Gah, I messed it up _despite_ having asked you first! Oh well, I'll update the PR first thing tomorrow :smiley:

**Comment by troglobit** [comment]
Updated pull-request, hopefully I got the port:dev thingy right this time! :wink:

**Comment by wkz** [comment]
Great, thanks!

**Comment by troglobit** [comment]
Ossom, maybe soon then we'll see a v1.0 tagged? ;-)

**Comment by wkz** [comment]
Nope, there might be a v1 though :stuck_out_tongue_winking_eye:

**Pull request merged**
